language: python

python:
- '3.5'
- '3.6'

install:
- pip install -r dev-requirements.txt

script:
- pytest test/ -v
- pycodestyle commit_helper/* test/*

after_script:
- py.test --cov-report term --cov=. --ignore=test/* --cov-report=html
- codeclimate-test-reporter
- coverage xml
- python-codacy-coverage -r coverage.xml

notification:
  email: false

before_deploy:
  - echo 'Beggining deploy...'
  - python3 setup.py build
  - python3 setup.py sdist bdist_wheel

deploy:
  - provider: script
    script: bash deploy.sh deploy
    on:
      branch: master

  - provider: script
    script: bash deploy.sh test
    server: https://test.pypi.org/legacy/
    on:
      branch: development
